import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "ar";

const en = {
  dashboard: "Dashboard", trading: "Trading", market: "Market", strategies: "Strategies",
  risk: "Risk Management", botControl: "Bot Control", analytics: "Analytics",
  reports: "Reports", auditLogs: "Audit Logs", settings: "Settings", subscription: "Subscription",
  intelligence: "AI Intelligence", voiceChat: "AI Voice Chat", botManual: "Bot Manual", 
  themeEditor: "Theme Studio", liveActivity: "Live Activity", lockApp: "Lock App", logout: "Sign Out",
  signIn: "Sign In", switchAccount: "Switch Account",
  liveTrading: "Live Trading", paperTrading: "Paper Trading", overview: "Overview", market_: "Market",
  loading: "Loading", save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit",
  create: "Create", confirm: "Confirm", close: "Close", refresh: "Refresh", done: "Done",
  search: "Search", filter: "Filter", export: "Export", import: "Import", apply: "Apply",
  back: "Back", next: "Next", submit: "Submit", skip: "Skip", enable: "Enable", disable: "Disable",
  dashboard_: "Dashboard", paperBalance: "Paper Balance",
  accountBalance: "Account Balance", totalPnL: "Total P&L", winRate: "Win Rate",
  openPositions: "Open Positions", totalTrades: "Total Trades", activeStrategies: "Active Strategies",
  botStatus: "Bot Status", equityCurve: "Equity Curve", performance: "Performance",
  lastSync: "Last Sync", status: "Status", live: "LIVE", paused: "PAUSED",
  buy: "Buy", sell: "Sell", quantity: "Quantity", price: "Price", stopLoss: "Stop Loss",
  takeProfit: "Take Profit", orderBook: "Order Book", positions: "Positions", orders: "Orders",
  trades: "Trades", pair: "Pair", lastPrice: "Last Price", volume: "Volume",
  strategyName: "Strategy Name", strategyType: "Strategy Type", tradingPair: "Trading Pair",
  active: "Active", inactive: "Inactive", getSignal: "Get Signal", createStrategy: "Create Strategy",
  noStrategies: "No strategies yet", momentum: "Momentum", trend: "Trend",
  maxDailyLoss: "Max Daily Loss", maxPositionSize: "Max Position Size",
  maxConcurrentTrades: "Max Concurrent Trades", riskRewardRatio: "Risk:Reward Ratio",
  circuitBreaker: "Circuit Breaker", slippageLimit: "Slippage Limit", atrMultiplier: "ATR Multiplier",
  healthScore: "Health Score", botIntegration: "Bot Integration",
  botControlCenter: "Bot Control Center", startBot: "Start", stopBot: "Stop", pauseBot: "Pause",
  restartBot: "Restart", running: "Running", stopped: "Stopped", errors: "Errors",
  lastCycle: "Last Cycle", botHealth: "Bot Health", openPositionsMonitor: "Open Positions Monitor",
  checkNow: "Check Now", tradeSize: "Trade Size", configuration: "Configuration",
  language: "Language", theme: "Theme", notifications: "Notifications", security: "Security",
  appLock: "App Lock", pinLock: "PIN Lock", email: "Email", password: "Password",
  apiKey: "API Key", apiSecret: "API Secret", testConnection: "Test Connection",
  saveBinanceKeys: "Save & Enable Live Trading", liveMode: "LIVE MODE ACTIVE",
  success: "Success", failed: "Failed", warning: "Warning", error: "Error",
  connecting: "Connecting", connected: "Connected", disconnected: "Disconnected",
  monitoring: "Monitoring", nowTrading: "Now Trading", botActive: "BOT ACTIVE",
  sharpeRatio: "Sharpe Ratio", recentTrades: "Recent Trades",
  engineSimulation: "Engine Simulation", youTrade: "You Trade", liveActivity_: "Live Activity",
  memobotAi: "MEMOBOT AI", riskManagerLabel: "Risk Manager", themeStudio: "Theme Studio",
  adminTerminal: "Admin Terminal", masterControl: "Master Control", account: "Account",
  rescanEngine: "Re-Scan Engine", searchMarket: "Search Market", systemActive: "System Active",
  lockSyst: "Lock System", engine: "FX-PRO", primeIntelligence: "Prime Intelligence",
  masterTerminal: "Master Terminal", nodeHealth: "Node Health", activeNodes: "Active Nodes",
  billing: "Billing",  strategyIntelligence: "Strategy Intelligence", globalConfig: "Global Config",
  performanceMetrics: "Performance Metrics", activeDeployment: "Active Deployment Fleet",
  optimizedExecution: "Optimized Execution", liveStatus: "Live Status", marketPair: "Market Pair",
  execCount: "Exec Count", alphaWin: "Alpha/Win", allocated: "Allocated", modifyDna: "Modify DNA",
  liveAnalysis: "Live Analysis", globalOverrides: "Global Overrides", syncAll: "SYNC ALL",
  syncing: "SYNCING...", syncSuccess: "Synchronized", syncDesc: "Master Engine and Strategies are now in phase.",
  analysisReport: "Analysis Report", tradeHistory: "Trade History", downloadCsv: "Download CSV",
  subscriptionPlans: "Subscription Plans", currentPlan: "Current Plan", upgrade: "Upgrade",
  activeNodesDesc: "Network Nodes Active", engineState: "Engine State", masterTerminalDesc: "Global Account Federation & Control",
  waitingNetwork: "Waiting for Network Nodes...", welcomeBack: "Welcome Back",
  memobotSecure: "MEMOBOT SECURE", terminalAccessRequired: "Encrypted Terminal Access Required",
  clear: "Clear", authenticateSequence: "AUTHENTICATE SEQUENCE", invalidPin: "Invalid PIN",
  proVersion: "PRO VERSION", pro: "PRO", trader: "Trader", arabic: "Arabic", english: "English",
  realProtocol: "REAL PROTOCOL", demoProtocol: "DEMO PROTOCOL", automated: "Automated",
  warningActiveExposure: "WARNING: ACTIVE EXPOSURE", masterDnaLocked: "Master DNA Locked",
  today: "Today", filled: "FILLED", completed: "COMPLETED", secondsAgo: "seconds ago",
  minutesAgo: "minutes ago", executionSuccessful: "Execution Successful", 
  orderFilledAt: "order filled at", executionRefused: "Execution Refused",
  master: "MASTER", terminal: "TERMINAL", liveNetworkActive: "LIVE NETWORK ACTIVE",
  highVelocityDeployment: "High-Velocity Deployment", realSignal: "REAL SIGNAL",
  synchronized: "SYNCHRONIZED", binanceLive: "BINANCE LIVE", binanceSpot: "Binance Spot",
  markPrice: "Mark Price", wallet: "Wallet", max: "MAX", 
  advancedAnalystOptions: "Advanced Analyst Options", stopLossLabel: "Stop Loss",
  takeProfitLabel: "Take Profit", leverageLabel: "Leverage", 
  deployingSequence: "DEPLOYING SEQUENCE...", confirmLong: "CONFIRM LONG",
  confirmShort: "CONFIRM SHORT", exploit: "EXPLOIT", atMarketPrice: "AT MARKET PRICE",
  analystIntelligenceUnit: "Analyst Intelligence Unit", signalHighStrength: "Signal: High Strength",
  alphaWinLabel: "Alpha-Win", liquidityAggregator: "Liquidity Aggregator",
  openPositionInventory: "Open Position Inventory", viewAllHistory: "VIEW ALL HISTORY",
  index: "INDEX", asset: "ASSET", side: "SIDE", sizeIncLev: "SIZE (INC. LEV)",
  unrealizedRoi: "UNREALIZED ROI", noActiveInventory: "NO ACTIVE INVENTORY",
  masterExecutionTerminal: "Master Execution Terminal", coreOperationsEngine: "Core Operations Engine",
  aiGuardActive: "AI GUARD ACTIVE", latency: "Latency", voiceControl: "Voice Control",
  executeViaSpeech: "Execute via speech", voiceProtocolInitialized: "Voice Recognition Protocol Initialized",
  signalAlertsActive: "Signal alerts active", realModeProtocol: "REAL MODE PROTOCOL",
  paperModeProtocol: "PAPER MODE PROTOCOL", liveCapitalAtRisk: "LIVE CAPITAL AT RISK",
  virtualTestingEnvironment: "VIRTUAL TESTING ENVIRONMENT", restricted: "RESTRICTED",
  safe: "SAFE", criticalWarningRealMode: "CRITICAL WARNING: You are entering REAL MODE. MEMOBOT will now execute trades using actual terminal funds. Do you wish to continue?",
  transactionIntelligenceMonitor: "Transaction Intelligence Monitor", 
  liveSequenceSync: "Live Sequence Sync", executionId: "Execution ID",
  realUsdt: "REAL USDT", demoUsdt: "DEMO USDT",
  strategies_: "Strategies",
  multiStrategyDeployment: "Multi-Strategy Quantitative Deployment",
  noStrategies_: "No Active Strategies",
  clickToDeployFirst: "Click \"Create Strategy\" above to deploy your first automated trading agent.",
  strategySequenceInitialized: "Strategy Sequence Initialized",
  strategyStateShifted: "Strategy State Shifted",
  strategyDissolved: "Strategy Dissolved",
  masterConfigTerminalAccess: "Master Config Terminal Access Req.",
  riskProtocols: "RISK PROTOCOLS",
  activeSurveillance: "Active Surveillance & Capital Protection",
  riskProtocolResynced: "Risk Protocol Re-Synchronized",
  manualOverrideActive: "Manual Override Active",
  riskDnaGoverned: "Engines and Strategies are now governed by Master Risk DNA.",
  riskSyncDetached: "Risk synchronization has been detached. Handle with extreme caution.",
  detached: "DETACHED",
  automatedDrawdownProtection: "Automated Drawdown Protection",
  circuitBreakerLogic: "Circuit breaker logic for market flash crashes",
  maxSessionDrawdown: "Max Session Drawdown",
  tailRiskHedging: "Tail Risk Hedging",
  smartRebalance: "Smart Rebalance",
  rebalanceDescription: "Automated engine will rebalance allocations if volatility exceeds ATR(20) threshold.",
  calibrateEmergencyCircuit: "CALIBRATE EMERGENCY CIRCUIT BREAKERS",
  tierAllocationDescription: "DNA for high frequency and trend following.",
  tier1Allocation: "Tier 1 Allocation",
  tier2Allocation: "Tier 2 Allocation",
  aggressive: "AGGRESSIVE",
  conservative: "CONSERVATIVE",
  highFrequencyScalpingDna: "High Frequency Scalping DNA",
  trendFollowingDna: "Trend Following DNA",
  leverageCap: "LEVERAGE CAP",
  syncEngineControl: "Sync Engine Control",
  autoSyncStrategies: "Auto-Sync Strategies",
  globalProfitGuard: "Global Profit Guard",
  apiLatencyKillswitch: "API Latency Killswitch",
  multiAccountMirror: "Multi-Account Mirror",
  forceResyncAll: "FORCE RE-SYNC ALL ENGINES",
  syncVerifiedCount: "Sync verified - 12 strategies currently orbiting",
  emergencyProtocol: "EMERGENCY PROTOCOL",
  liquidateAllAssets: "LIQUIDATE ALL ASSETS",
  instantlyCloseAll: "Instantly close all open positions across all strategies in 12ms. Action is irreversible.",
  executeKillConsole: "EXECUTE KILL CONSOLE",
  analyticsDescription: "Advanced quantitative trading metrics and risk exposure analysis",
  dayPeriod30: "30 Day Period",
  initializingAnalytics: "Initializing Analytics...",
  portfolioAlphaProjection: "Portfolio Alpha Projection & Equity Growth",
  liveEquity: "Live Equity",
  baseline: "Baseline",
  clickForDetails: "Click for details",
  maxDrawdownDescription: "The maximum peak-to-trough decline during a specific record period.",
  sharpeRatioDescription: "Measures the performance of an investment compared to a risk-free asset.",
  sortinoRatioDescription: "Similar to Sharpe but only penalizes downside volatility. Higher is better.",
  platformEngineering: "PLATFORM ENGINEERING",
  coreSystemConfig: "Core system configuration & exchange connectivity",
  binanceConnection: "Binance Exchange Connection",
  requiredReadWrite: "Required for read/write",
  neverShareKey: "Never share this key",
  activateConnection: "ACTIVATE CONNECTION",
  testing: "TESTING...",
  testAuth: "TEST AUTH",
  connectingToBinance: "Connecting to Binance servers...",
  binanceConnectivityVerified: "Binance Connectivity Verified",
  apiStatusOnline: "API Status: ONLINE | Latency: 42ms | Permissions: TRADE, READ",
  securityAndAppLock: "Security & App Lock",
  pinProtection4Digit: "4-Digit PIN Protection",
  requirePinDescription: "Require PIN authentication on startup and inactivity.",
  settingsSaved: "settings saved",
  protocols: "PROTOCOLS",
  aggressive_: "AGGRESSIVE",
  conservative_: "CONSERVATIVE",
  maxSessionDrawdown_: "Max Session Drawdown",
  engineConfigSynced: "Engine Configuration Synced",
  voiceRecognitionInitialized: "Voice Recognition Protocol Initialized",
  botStatusPrefix: "Bot",
  executionPrice: "Execution Price",
  delta24h: "Delta 24H",
  upperBound: "Upper Bound",
  lowerBound: "Lower Bound",
  tradeVolume: "Trade Volume",
  engineChart: "Engine Chart",
  rsiMomentum: "RSI Momentum (14)",
  macdDivergence: "MACD Divergence",
  bollingerCorridor: "Bollinger Corridor",
  engineScore: "MEMOBOT Engine Score",
  neutralZone: "Neutral Zone",
  signalLabel: "Signal",
  volatilityLow: "Volatility: LOW",
  accumulationPhase: "Accumulation Phase",
  neuralNetworkPrediction: "Neural Network Market Prediction & Optimization",
  ensembleVerdict: "Ensemble Verdict",
  indicatorAnalysisDesc: "Cross-analysis of 14 technical & sentiment indicators",
  masterRating: "Master Rating",
  confidence: "Confidence",
  analyzing: "ANALYZING",
  riskBias: "Risk Bias",
  neutral: "NEUTRAL",
  processingSequence: "PROCESSING QUANT SEQUENCE...",
  executeOptimizedTrade: "EXECUTE AI-OPTIMIZED TRADE SEQUENCE",
  proprietaryOptimizations: "Proprietary Optimizations",
  applyAllOptimizations: "APPLY ALL OPTIMIZATIONS",
  bullish: "Bullish",
  bearish: "Bearish",
  recalculatingMarketDna: "Recalculating Market DNA...",
  ensembleAnalysisComplete: "Ensemble Analysis Complete",
  synapticLinkFailed: "Synaptic Link Failed",
  reportsDescription: "Detailed performance summaries and trade logs.",
  realTimeExecutionRegistry: "Real-time Execution Registry",
  liveSyncing: "Live Syncing",
  timestamp: "Timestamp",
  assetPair: "Asset Pair",
  executionSide: "Execution Side",
  entryPrice: "Entry Price",
  deltaNetPnl: "Delta Net (PnL)",
  binanceExecution: "Binance Execution",
  dailySummary: "Daily Summary",
  dailySummaryDesc: "Consolidated view of all trades executed in the last 24 hours.",
  weeklyRiskAudit: "Weekly Risk Audit",
  weeklyRiskAuditDesc: "Detailed risk violation logs and circuit breaker events.",
  monthlyRoi: "Monthly ROI",
  monthlyRoiDesc: "Profit/Loss distribution across all strategies for this month.",
  last7Days: "Last 7 Days",
  may2024: "May 2024",
  billingAndSubscriptionDesc: "Manage your engine access level",
  recommended: "Recommended",
  month: "mo",
  paymentMethods: "Payment Methods",
  cryptoCurrency: "Cryptocurrency (USDT/BTC)",
  autoActivationDesc: "Auto-activation after 1 confirmation",
  uaeGateways: "UAE Gateways",
  aedDomesticSupport: "AED Domestic Support",
  globalCoverage: "Global Coverage",
  secureTransactions: "Secure Transactions",
  secureTransactionsDesc: "All payments are encrypted and processed through segregated gateways. No card data is stored on our servers.",
  starter: "Starter",
  professional: "Professional",
  institutional: "Institutional",
  free: "Free",
  networkHealth: "Network Health",
  terminate: "TERMINATE",
  elite: "Elite"
};

const ar = {
  dashboard: "لوحة التحكم", trading: "التداول", market: "السوق", strategies: "الاستراتيجيات",
  risk: "إدارة المخاطر", botControl: "التحكم بالروبوت", analytics: "التحليلات",
  reports: "التقارير", auditLogs: "سجل المراجعة", settings: "الإعدادات", subscription: "الاشتراك",
  intelligence: "الذكاء الاصطناعي", voiceChat: "محادثة صوتية", botManual: "دليل الروبوت",
  themeEditor: "محرر المظهر", liveActivity: "النشاط المباشر", lockApp: "قفل التطبيق", logout: "تسجيل الخروج",
  signIn: "تسجيل الدخول", switchAccount: "تبديل الحساب",
  liveTrading: "التداول الفعلي", paperTrading: "التداول الورقي", overview: "نظرة عامة", market_: "السوق",
  loading: "جاري التحميل", save: "حفظ", cancel: "إلغاء", delete: "حذف", edit: "تعديل",
  create: "إنشاء", confirm: "تأكيد", close: "إغلاق", refresh: "تحديث", done: "تم",
  search: "بحث", filter: "تصفية", export: "تصدير", import: "استيراد", apply: "تطبيق",
  back: "رجوع", next: "التالي", submit: "إرسال", skip: "تخطي", enable: "تفعيل", disable: "تعطيل",
  dashboard_: "لوحة التحكم", paperBalance: "الرصيد التجريبي",
  accountBalance: "رصيد الحساب", totalPnL: "إجمالي الربح/الخسارة", winRate: "معدل الفوز",
  openPositions: "المراكز المفتوحة", totalTrades: "إجمالي الصفقات", activeStrategies: "الاستراتيجيات النشطة",
  botStatus: "حالة الروبوت", equityCurve: "منحنى الأسهم", performance: "الأداء",
  lastSync: "آخر مزامنة", status: "الحالة", live: "مباشر", paused: "موقوف",
  buy: "شراء", sell: "بيع", quantity: "الكمية", price: "السعر", stopLoss: "وقف الخسارة",
  takeProfit: "جني الأرباح", orderBook: "دفتر الأوامر", positions: "المراكز", orders: "الأوامر",
  trades: "الصفقات", pair: "الزوج", lastPrice: "آخر سعر", volume: "الحجم",
  strategyName: "اسم الاستراتيجية", strategyType: "نوع الاستراتيجية", tradingPair: "زوج التداول",
  active: "نشط", inactive: "غير نشط", getSignal: "احصل على إشارة", createStrategy: "إنشاء الاستراتيجية",
  noStrategies: "لا توجد استراتيجيات حتى الآن", momentum: "الزخم", trend: "الاتجاه",
  maxDailyLoss: "أقصى خسارة يومية", maxPositionSize: "أقصى حجم مركز",
  maxConcurrentTrades: "أقصى صفقات متزامنة", riskRewardRatio: "نسبة المخاطرة/العائد",
  circuitBreaker: "قاطع الدائرة", slippageLimit: "حد الانزلاق", atrMultiplier: "مضاعف ATR",
  healthScore: "درجة الصحة", botIntegration: "تكامل الروبوت",
  botControlCenter: "مركز التحكم بالروبوت", startBot: "ابدأ", stopBot: "توقف", pauseBot: "إيقاف مؤقت",
  restartBot: "إعادة تشغيل", running: "يعمل", stopped: "متوقف", errors: "الأخطاء",
  lastCycle: "آخر دورة", botHealth: "صحة الروبوت", openPositionsMonitor: "مراقب المراكز المفتوحة",
  checkNow: "تحقق الآن", tradeSize: "حجم الصفقة", configuration: "الإعدادات",
  language: "اللغة", theme: "المظهر", notifications: "الإشعارات", security: "الأمان",
  appLock: "قفل التطبيق", pinLock: "قفل PIN", email: "البريد الإلكتروني", password: "كلمة المرور",
  apiKey: "مفتاح API", apiSecret: "سر API", testConnection: "اختبر الاتصال",
  saveBinanceKeys: "حفظ وتفعيل التداول الفعلي", liveMode: "وضع مباشر نشط",
  success: "نجاح", failed: "فشل", warning: "تحذير", error: "خطأ",
  connecting: "جاري الاتصال", connected: "متصل", disconnected: "غير متصل",
  monitoring: "مراقبة", nowTrading: "يتداول الآن", botActive: "الروبوت نشط",
  sharpeRatio: "نسبة شارب", recentTrades: "الصفقات الأخيرة",
  engineSimulation: "محاكاة المحرك", youTrade: "تداولاتك", liveActivity_: "النشاط المباشر",
  memobotAi: "ميموبوت ذكاء اصطناعي", riskManagerLabel: "مدير المخاطر", themeStudio: "استوديو المظهر",
  adminTerminal: "محطة المسؤول", masterControl: "التحكم الرئيسي", account: "الحساب",
  rescanEngine: "إعادة فحص المحرك", searchMarket: "البحث في السوق", systemActive: "النظام نشط",
  lockSyst: "قفل النظام", engine: "إف إكس برو", primeIntelligence: "الذكاء الخارق",
  masterTerminal: "المحطة الرئيسية", nodeHealth: "صحة العقدة", activeNodes: "العقد النشطة",
  billing: "الفواتير", strategyIntelligence: "ذكاء الاستراتيجية", globalConfig: "الإعدادات العامة",
  performanceMetrics: "مقاييس الأداء", activeDeployment: "أسطول النشر المباشر",
  optimizedExecution: "تنفيذ محسن", liveStatus: "الحالة المباشرة", marketPair: "زوج السوق",
  execCount: "عدد التنفيذي", alphaWin: "ألفا/ربح", allocated: "مخصص", modifyDna: "تعديل DNA",
  liveAnalysis: "تحليل مباشر", globalOverrides: "تجاوزات عامة", syncAll: "مزامنة الكل",
  syncing: "جاري المزامنة...", syncSuccess: "متزامن", syncDesc: "المحرك الرئيسي والاستراتيجيات الآن في مرحلة متوافقة.",
  analysisReport: "تقرير التحليل", tradeHistory: "سجل التداول", downloadCsv: "تحميل CSV",
  subscriptionPlans: "خطط الاشتراك", currentPlan: "الخطة الحالية", upgrade: "ترقية",
  activeNodesDesc: "عقد الشبكة النشطة", engineState: "حالة المحرك", masterTerminalDesc: "اتحاد الحسابات العالمي والتحكم",
  waitingNetwork: "بانتظار عقد الشبكة...", welcomeBack: "مرحباً بعودتك",
  memobotSecure: "ميموبوت آمن", terminalAccessRequired: "مطلوب وصول مشفر للمحطة",
  clear: "مسح", authenticateSequence: "تسلسل المصادقة", invalidPin: "رقم التعريف الشخصي غير صالح",
  proVersion: "إصدار برو", pro: "برو", trader: "متداول", arabic: "العربية", english: "الإنجليزية",
  realProtocol: "بروتوكول حقيقي", demoProtocol: "بروتوكول تجريبي", automated: "مؤتمت",
  warningActiveExposure: "تحذير: تعرض نشط", masterDnaLocked: "تم قفل Master DNA",
  today: "اليوم", filled: "مكتمل", completed: "ناجح", secondsAgo: "ثوانٍ مضت",
  minutesAgo: "دقائق مضت", executionSuccessful: "تم التنفيذ بنجاح", 
  orderFilledAt: "تم ملء الأمر عند", executionRefused: "تم رفض التنفيذ",
  strategies_: "الاستراتيجيات",
  multiStrategyDeployment: "النشر المتعدد للاستراتيجيات الكمية",
  noStrategies_: "لا توجد استراتيجيات نشطة",
  clickToDeployFirst: "انقر فوق 'إنشاء استراتيجية' أعلاه لنشر أول وكيل تداول آلي خاص بك.",
  strategySequenceInitialized: "تم بدء تسلسل الاستراتيجية",
  strategyStateShifted: "تم تغيير حالة الاستراتيجية",
  strategyDissolved: "تم حل الاستراتيجية",
  masterConfigTerminalAccess: "مطلوب الوصول إلى محطة التكوين الرئيسية",
  riskProtocols: "بروتوكولات المخاطر",
  activeSurveillance: "المراقبة النشطة وحماية رأس المال",
  riskProtocolResynced: "تم إعادة مزامنة بروتوكول المخاطر",
  manualOverrideActive: "التجاوز اليدوي نشط",
  riskDnaGoverned: "المحركات والاستراتيجيات الآن تحت حكم حمض المخاطر النووي الرئيسي.",
  riskSyncDetached: "تم فصل مزامنة المخاطر. تعامل بحذر شديد.",
  detached: "منفصل",
  automatedDrawdownProtection: "حماية السحب الآلي",
  circuitBreakerLogic: "منطق قاطع الدائرة لتقلبات السوق الفجائية",
  maxSessionDrawdown: "الحد الأقصى للسحب للجلسة",
  tailRiskHedging: "تحوط مخاطر الذيل",
  smartRebalance: "إعادة التوازن الذكي",
  rebalanceDescription: "سيقوم المحرك الآلي بإعادة توازن التخصيصات إذا تجاوز التقلب عتبة ATR(20).",
  calibrateEmergencyCircuit: "معايرة قواطع الدوائر في حالات الطوارئ",
  tierAllocationDescription: "DNA للترددات العالية وتتبع الاتجاه.",
  tier1Allocation: "تخصيص المستوى ١",
  tier2Allocation: "تخصيص المستوى ٢",
  aggressive: "عدواني",
  conservative: "محافظ",
  highFrequencyScalpingDna: "DNA سكالبينج عالي التردد",
  trendFollowingDna: "DNA تتبع الاتجاه",
  leverageCap: "سقف الرافعة المالية",
  syncEngineControl: "التحكم في مزامنة المحرك",
  autoSyncStrategies: "مزامنة الاستراتيجيات تلقائياً",
  globalProfitGuard: "حماية الربح العالمية",
  apiLatencyKillswitch: "مفتاح قتل زمن الوصول API",
  multiAccountMirror: "مرآة الحسابات المتعددة",
  forceResyncAll: "فرض إعادة مزامنة جميع المحركات",
  syncVerifiedCount: "تم التحقق من المزامنة - ١٢ استراتيجية تدور حالياً",
  emergencyProtocol: "بروتوكول الطوارئ",
  liquidateAllAssets: "تسييل جميع الأصول",
  instantlyCloseAll: "أغلق فوراً جميع الصفقات المفتوحة عبر جميع الاستراتيجيات في ١٢ مللي ثانية. الإجراء لا يمكن التراجع عنه.",
  executeKillConsole: "تنفيذ وحدة التحكم في القتل",
  analyticsDescription: "مقاييس التداول الكمي المتقدمة وتحليل التعرض للمخاطر",
  dayPeriod30: "فترة ٣٠ يوماً",
  initializingAnalytics: "جاري تهيئة التحليلات...",
  portfolioAlphaProjection: "إسقاط المحفظة ونمو حقوق الملكية",
  liveEquity: "حقوق الملكية المباشرة",
  baseline: "خط الأساس",
  clickForDetails: "اضغط للمزيد",
  maxDrawdownDescription: "الحد الأقصى للسحب من الذروة خلال فترة زمنية محددة.",
  sharpeRatioDescription: "يقيس أداء الاستثمار مقارنة بالأصول الخالية من المخاطر بعد التعديل.",
  sortinoRatioDescription: "مشابه لشارب ولكنه يعاقب فقط التقلبات السلبية. الأعلى أفضل.",
  platformEngineering: "هندسة المنصة",
  coreSystemConfig: "تكوين النظام الأساسي واتصال البورصة",
  binanceConnection: "اتصال بورصة باينانس",
  requiredReadWrite: "مطلوب للقراءة/الكتابة",
  neverShareKey: "لا تشارك هذا المفتاح أبداً",
  activateConnection: "تفعيل الاتصال",
  testing: "جاري الاختبار...",
  testAuth: "اختبار المصادقة",
  connectingToBinance: "جاري الاتصال بخوادم باينانس...",
  binanceConnectivityVerified: "تم التحقق من اتصال باينانس",
  apiStatusOnline: "حالة API: متصل | زمن الوصول: ٤٢ مللي ثانية | الأذونات: تداول، قراءة",
  securityAndAppLock: "الأمان وقفل التطبيق",
  pinProtection4digit: "حماية PIN من ٤ أرقام",
  requirePinDescription: "تطلب مصادقة PIN عند بدء التشغيل وعدم النشاط.",
  settingsSaved: "تم حفظ الإعدادات",
  protocols: "بروتوكولات",
  aggressive_: "عدواني",
  conservative_: "محافظ",
  maxSessionDrawdown_: "الحد الأقصى للسحب للجلسة",
  engineConfigSynced: "تم مزامنة تكوين المحرك",
  voiceRecognitionInitialized: "تم تهيئة بروتوكول التعرف على الصوت",
  botStatusPrefix: "البوت",
  executionPrice: "سعر التنفيذ",
  delta24h: "دلتا ٢٤ ساعة",
  upperBound: "الحد الأعلى",
  lowerBound: "الحد الأدنى",
  tradeVolume: "حجم التداول",
  engineChart: "مخطط المحرك",
  rsiMomentum: "زخم RSI (١٤)",
  macdDivergence: "تباعد MACD",
  bollingerCorridor: "ممر بولينجر",
  engineScore: "نقاط محرك ميموبوت",
  neutralZone: "منطقة محايدة",
  signalLabel: "الإشارة",
  volatilityLow: "التقلب: منخفض",
  accumulationPhase: "مرحلة التجميع",
  binanceSpot: "باينانس فوري",
  neuralNetworkPrediction: "تنبؤ وتحسين السوق عبر الشبكة العصبية",
  ensembleVerdict: "الحكم الجماعي",
  indicatorAnalysisDesc: "تحليل متقاطع لـ ١٤ مؤشراً فنياً ومشاعرياً",
  masterRating: "التصنيف الرئيسي",
  confidence: "الثقة",
  analyzing: "جاري التحليل",
  riskBias: "انحياز المخاطر",
  neutral: "محايد",
  processingSequence: "جاري معالجة التسلسل الكمي...",
  executeOptimizedTrade: "تنفيذ تسلسل تداول محسن بالذكاء الاصطناعي",
  proprietaryOptimizations: "تحسينات ملكية",
  applyAllOptimizations: "تطبيق جميع التحسينات",
  bullish: "متفائل",
  bearish: "متشائم",
  recalculatingMarketDna: "جاري إعادة حساب DNA السوق...",
  ensembleAnalysisComplete: "اكتمل تحليل المجموعة",
  synapticLinkFailed: "فشل الارتباط المشبكي",
  reportsDescription: "ملخصات الأداء التفصيلية وسجلات التداول.",
  realTimeExecutionRegistry: "سجل التنفيذ في الوقت الفعلي",
  liveSyncing: "مزامنة مباشرة",
  timestamp: "الطابع الزمني",
  assetPair: "زوج الأصول",
  executionSide: "جانب التنفيذ",
  entryPrice: "سعر الدخول",
  deltaNetPnl: "صافي دلتا (الربح والخسارة)",
  binanceExecution: "تنفيذ باينانس",
  dailySummary: "ملخص يومي",
  dailySummaryDesc: "عرض موحد لجميع الصفقات المنفذة في آخر ٢٤ ساعة.",
  weeklyRiskAudit: "تدقيق المخاطر الأسبوعي",
  weeklyRiskAuditDesc: "سجلات انتهاك المخاطر المفصلة وأحداث قاطع الدائرة.",
  monthlyRoi: "العائد الشهري على الاستثمار",
  monthlyRoiDesc: "توزيع الأرباح/الخسائر عبر جميع الاستراتيجيات لهذا الشهر.",
  last7Days: "آخر ٧ أيام",
  may2024: "مايو ٢٠٢٤",
  billingAndSubscriptionDesc: "إدارة مستوى الوصول للمحرك الخاص بك",
  recommended: "موصى به",
  month: "شهر",
  paymentMethods: "طرق الدفع",
  cryptoCurrency: "العملات الرقمية (USDT/BTC)",
  autoActivationDesc: "تفعيل تلقائي بعد تأكيد واحد",
  uaeGateways: "بوابات الإمارات",
  aedDomesticSupport: "دعم محلي بالدرهم",
  globalCoverage: "تغطية عالمية",
  secureTransactions: "معاملات آمنة",
  secureTransactionsDesc: "تم تشفير جميع المدفوعات ومعالجتها من خلال بوابات منفصلة. لا يتم تخزين بيانات البطاقة على خوادمنا.",
  starter: "بداية",
  professional: "احترافي",
  institutional: "مؤسسي",
  free: "مجاني",
  networkHealth: "صحة الشبكة",
  terminate: "إنهاء",
  elite: "نخبة"
};

const translations = { en, ar };

const arabicDigitsMap: Record<string, string> = {
  '0': '٠', '1': '١', '2': '٢', '3': '٣', '4': '٤', '5': '٥', '6': '٦', '7': '٧', '8': '٨', '9': '٩',
  '.': '٫', ',': '٬', '%': '٪'
};

export type TranslationKey = keyof typeof en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
  f: (val: string | number) => string; 
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en", setLanguage: () => {}, t: (key) => key as string, isRTL: false, f: (v) => String(v),
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("memobot_lang") as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("memobot_lang", lang);
  };

  const isRTL = language === "ar";

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: TranslationKey): string => (translations[language] as any)[key] || (translations.en as any)[key] || key;

  const f = (val: string | number): string => {
    const s = String(val);
    if (!isRTL) return s;
    return s.split('').map(char => arabicDigitsMap[char] || char).join('');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, f }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
